### CREER UNE CATÉGORIE
POST http://localhost:5000/api/category
Content-Type: application/json

{"category_name":"restau"}

###CONSULTER TOUTES LES CATÉGORIES
GET http://localhost:5000/api/category

###CONSULTER UNE CATÉGORIE AC SON ID
GET http://localhost:5000/api/category/1

###MODIFIER UNE CATÉGORIE
PUT http://localhost:5000/api/category/2
Content-Type: application/json

{"category_name":"aventure"}

###SUPPRIMER UNE CATÉGORIE
DELETE http://localhost:5000/api/category/1

###CONSULTER TOUS LES CONTINENTS
GET http://localhost:5000/api/continent

###CONSULTER UN CONTINENT AC SON ID
GET http://localhost:5000/api/continent/2

### CREER UN VOYAGE
POST http://localhost:5000/api/trip
Content-Type: application/json

{"destination":"Sri Lanka",
"picture":"https://www.parcourscanada.com/wp-content/uploads/2018/12/tdb_003yDJ0248DC0ce5xs8x.jpg",
"tips":"Nuit en bivouac dans le désert du Sahara. Super adresse à l'Auberge du Sud. Au programme : coucher de soleil, observation des étoiles, promenade dans le désert et repas traditionnel",
"continent_id":1}

###CONSULTER TOUS LES VOYAGES
GET http://localhost:5000/api/trips

###CONSULTER UN VOYAGE AC SON ID
GET http://localhost:5000/api/trip/8

###MODIFIER UN VOYAGE
PUT http://localhost:5000/api/trip/48
Content-Type: application/json

{"tips":"Tip : si votre budget le permet, offrez-vous un baptème de l'air en hydravion au dessus du lac de la Mauritie, c'est magique"}

###SUPPRIMER UN VOYAGE
DELETE http://localhost:5000/api/trip/28





