### CREER UNE CATÉGORIE
POST http://localhost:5000/api/category
Content-Type: application/json

{"category_name":"restau"}

###CONSULTER TOUTES LES CATÉGORIES
GET http://localhost:5000/api/category

###CONSULTER UNE CATÉGORIE AC SON ID
GET http://localhost:5000/api/category/1

###MODIFIER UNE CATÉGORIE
PUT http://localhost:5000/api/category/2
Content-Type: application/json

{"category_name":"aventure"}

###SUPPRIMER UNE CATÉGORIE
DELETE http://localhost:5000/api/category/1

###CONSULTER TOUS LES CONTINENTS
GET http://localhost:5000/api/continent

###CONSULTER UN CONTINENT AC SON ID
GET http://localhost:5000/api/continent/2

### CREER UN VOYAGE
POST http://localhost:5000/api/trip
Content-Type: application/json

{"destination":"Sri Lanka",
"picture":"https://zupimages.net/viewer.php?id=20/30/4p6x.jpg",
"tips":"Randonnée Adam's Peak de nuit pendant la période du pélérinage",
"continent_id":4}

###CONSULTER TOUS LES VOYAGES
GET http://localhost:5000/api/trip

###CONSULTER UN VOYAGE AC SON ID
GET http://localhost:5000/api/trip/8

###MODIFIER UN VOYAGE
PUT http://localhost:5000/api/trip/8
Content-Type: application/json

{"tips":"test"}

###SUPPRIMER UN VOYAGE
DELETE http://localhost:5000/api/trip/7





